# Generated by Django 4.0.1 on 2022-02-01 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('by', models.TextField(default=None, null=True)),
                ('item_id', models.TextField(default=None, null=True)),
                ('score', models.TextField(default=None, null=True)),
                ('time', models.TextField(default=None, null=True)),
                ('title', models.TextField(default=None, null=True)),
                ('item_type', models.TextField(default=None, null=True)),
                ('descendants', models.TextField(default=None, null=True)),
                ('kids', models.TextField(default=None, null=True)),
                ('text', models.TextField(default=None, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('ask', 'ASK'), ('show', 'SHOW'), ('new', 'NEW'), ('work', 'WORK')], default='new', max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('by', models.TextField(default=None, null=True)),
                ('item_id', models.TextField(default=None, null=True)),
                ('score', models.TextField(default=None, null=True)),
                ('time', models.TextField(default=None, null=True)),
                ('title', models.TextField(default=None, null=True)),
                ('item_type', models.TextField(default=None, null=True)),
                ('url', models.TextField(default=None, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='New',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('by', models.TextField(default=None, null=True)),
                ('item_id', models.TextField(default=None, null=True)),
                ('score', models.TextField(default=None, null=True)),
                ('time', models.TextField(default=None, null=True)),
                ('title', models.TextField(default=None, null=True)),
                ('item_type', models.TextField(default=None, null=True)),
                ('descendants', models.TextField(default=None, null=True)),
                ('kids', models.TextField(default=None, null=True)),
                ('text', models.TextField(default=None, null=True)),
                ('url', models.TextField(default=None, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Show',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('by', models.TextField(default=None, null=True)),
                ('item_id', models.TextField(default=None, null=True)),
                ('score', models.TextField(default=None, null=True)),
                ('time', models.TextField(default=None, null=True)),
                ('title', models.TextField(default=None, null=True)),
                ('item_type', models.TextField(default=None, null=True)),
                ('descendants', models.TextField(default=None, null=True)),
                ('kids', models.TextField(default=None, null=True)),
                ('url', models.TextField(default=None, null=True)),
            ],
        ),
    ]
