# Generated by Django 4.0.1 on 2022-02-01 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='choice',
            name='name',
            field=models.CharField(choices=[('askstories', 'ASK'), ('showstories', 'SHOW'), ('newstories', 'NEW'), ('jobstories', 'JOB')], default='new', max_length=40),
        ),
    ]
