# Generated by Django 4.0.1 on 2022-02-01 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0002_alter_choice_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ask',
            name='id',
        ),
        migrations.RemoveField(
            model_name='job',
            name='id',
        ),
        migrations.RemoveField(
            model_name='new',
            name='id',
        ),
        migrations.RemoveField(
            model_name='show',
            name='id',
        ),
        migrations.AlterField(
            model_name='ask',
            name='item_id',
            field=models.IntegerField(default=0, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='job',
            name='item_id',
            field=models.IntegerField(default=0, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='new',
            name='item_id',
            field=models.IntegerField(default=0, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='show',
            name='item_id',
            field=models.IntegerField(default=0, primary_key=True, serialize=False),
        ),
    ]
