# Generated by Django 4.0.2 on 2022-02-08 12:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_shopusertest'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shopusertest',
            name='is_superuser',
        ),
    ]
