# Generated by Django 4.0.2 on 2022-02-08 16:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_remove_shopusertest_is_superuser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ShopUser',
        ),
    ]
