# Generated by Django 4.0.2 on 2022-02-08 16:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_delete_shopuser'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ShopUserTest',
            new_name='ShopUser',
        ),
    ]
