# Generated by Django 4.0.2 on 2022-02-08 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_rename_shopusertest_shopuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopuser',
            name='is_superuser',
            field=models.BooleanField(default=False),
        ),
    ]
